apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-database
spec:
  replicas: 3
  selector:
    app: database
  template:
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: caddy
          ports:
            - containerPort: 80
