apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pet
  labels:
    app: secret-pet
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: secret-pet
  template:
    metadata:
      labels:
        app: secret-pet
    spec:
      containers:
        - name: secret-pet-image
          image: glockers/k8s-pet-project
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: person
